ENTRY_PACKET = 1
LEAVE_PACKET = 2
ALIVE_PACKET = 3

CALIBRATION_REQUEST = 40
CALIBRATION_RESPONSE = 41
CALIBRATION_ACK = 42

VALUE_REQUEST = 70
VALUE_REQUEST_ACK = 71
VALUE_RESPONSE = 72
VALUE_ERR_INVALID_TARGET = 73

#partial transfer stuff
PARTIAL_TRANSFER_ID_REQUEST = 74
PARTIAL_TRANSFER_ID_RESPONSE = 75
PARTIAL_TRANSFER = 76
PARTIAL_TRANSFER_ACK = 77
PARTIAL_TRANSFER_FINISHED = 78
PARTIAL_TRANSFER_FINISHED_ACK = 79

SENSOR_REGISTER_PACKET = 80
SENSOR_REGISTER_ACK_PACKET = 81
SENSOR_UNREGISTER_PACKET = 82
SENSOR_UNREGISTER_ACK_PACKET = 83
